version: '3.7'

volumes:
  pg_data:
    driver: local

services:

  server:
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/web
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web
