-- upgrade --
CREATE TABLE IF NOT EXISTS "carmodel" (
    "id" UUID NOT NULL  PRIMARY KEY,
    "model" VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS "event" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSONB NOT NULL
);
